-- Generated by tools/migrate-old-goods.mjs.
-- Source: https://g9p7q0i2-20260513.top/marketing/spu/spus
SET NAMES utf8mb4;

DROP TABLE IF EXISTS goods_import_stage_20260724;
CREATE TABLE goods_import_stage_20260724 (
    source_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    title TEXT NOT NULL,
    subtitle TEXT NULL,
    source_pic VARCHAR(1000) NULL,
    local_image VARCHAR(500) NOT NULL,
    price DECIMAL(20, 2) NOT NULL,
    seq BIGINT NOT NULL,
    enabled CHAR(1) NOT NULL,
    unit_price DECIMAL(20, 2) NULL,
    quantity INT NULL,
    star DECIMAL(10, 2) NULL,
    rate DECIMAL(10, 2) NULL,
    description LONGTEXT NULL,
    created_by VARCHAR(64) NULL,
    created_date DATETIME NULL,
    updated_date DATETIME NULL,
    source_data JSON NOT NULL,
    PRIMARY KEY (source_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

LOAD DATA LOCAL INFILE 'E:/code/order/java-admin-new-code/sql/migration_20260724/old-goods.tsv'
INTO TABLE goods_import_stage_20260724
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' ESCAPED BY '\\'
LINES TERMINATED BY '\n'
(source_id, category_id, title, subtitle, source_pic, local_image, price, seq,
 enabled, unit_price, quantity, star, rate, description, created_by,
 created_date, updated_date, source_data);

DROP TABLE IF EXISTS goods_type_import_stage_20260724;
CREATE TABLE goods_type_import_stage_20260724 (
    source_id BIGINT NOT NULL,
    title VARCHAR(300) NOT NULL,
    enabled CHAR(1) NOT NULL,
    seq BIGINT NOT NULL,
    image VARCHAR(500) NULL,
    subtitle VARCHAR(500) NULL,
    remark VARCHAR(500) NULL,
    created_date DATETIME NULL,
    source_data JSON NOT NULL,
    PRIMARY KEY (source_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

LOAD DATA LOCAL INFILE 'E:/code/order/java-admin-new-code/sql/migration_20260724/old-goods-types.tsv'
INTO TABLE goods_type_import_stage_20260724
CHARACTER SET utf8mb4
FIELDS TERMINATED BY '\t' ESCAPED BY '\\'
LINES TERMINATED BY '\n'
(source_id, title, enabled, seq, image, subtitle, remark, created_date, source_data);

DROP PROCEDURE IF EXISTS assert_old_goods_import_20260724;
DELIMITER $$
CREATE PROCEDURE assert_old_goods_import_20260724()
BEGIN
    IF (SELECT COUNT(*) FROM goods_import_stage_20260724) <> 44636 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Old goods staging row count mismatch';
    END IF;
    IF (SELECT COUNT(*) FROM goods_type_import_stage_20260724) <> 7 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Old goods category row count mismatch';
    END IF;
    IF EXISTS (
        SELECT 1 FROM goods_import_stage_20260724
        WHERE local_image IS NULL OR local_image = ''
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Old goods staging contains missing images';
    END IF;
END$$
DELIMITER ;
CALL assert_old_goods_import_20260724();
DROP PROCEDURE assert_old_goods_import_20260724;

SET @add_source_data_sql = IF(
    EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = DATABASE()
          AND table_name = 'goods'
          AND column_name = 'source_data'
    ),
    'SELECT 1',
    'ALTER TABLE goods ADD COLUMN source_data JSON NULL COMMENT ''原服务器完整商品数据'' AFTER description'
);
PREPARE add_source_data_stmt FROM @add_source_data_sql;
EXECUTE add_source_data_stmt;
DEALLOCATE PREPARE add_source_data_stmt;

ALTER TABLE goods
    MODIFY COLUMN title VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '标题',
    MODIFY COLUMN serial_number BIGINT NOT NULL COMMENT '原服务器序号',
    MODIFY COLUMN image VARCHAR(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '图片',
    MODIFY COLUMN sub_title VARCHAR(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '二级标题',
    MODIFY COLUMN star_rating DECIMAL(10, 2) NULL COMMENT '星级';

START TRANSACTION;

DELETE FROM goods;
DELETE FROM goods_type;

INSERT INTO goods_type (
    id, title, is_enabled, serial_number, image, sub_title, remarks, create_time
)
SELECT
    source_id,
    title,
    CASE enabled WHEN '1' THEN '0' ELSE '1' END,
    seq,
    COALESCE(image, ''),
    NULLIF(subtitle, ''),
    NULLIF(remark, ''),
    created_date
FROM goods_type_import_stage_20260724
ORDER BY source_id;

INSERT INTO goods (
    id, title, type_id, is_enabled, price, serial_number, image, sub_title,
    unit_price, quantity, star_rating, rating, description, source_data,
    create_by, create_time
)
SELECT
    source_id,
    title,
    category_id,
    CASE enabled WHEN '1' THEN '0' ELSE '1' END,
    price,
    seq,
    local_image,
    NULLIF(subtitle, ''),
    unit_price,
    quantity,
    star,
    rate,
    NULLIF(description, ''),
    source_data,
    created_by,
    created_date
FROM goods_import_stage_20260724
ORDER BY source_id;

COMMIT;

DROP TABLE goods_import_stage_20260724;
DROP TABLE goods_type_import_stage_20260724;

-- Explicit backup tables requested for removal.
DROP TABLE IF EXISTS goods_withdrawal_account_bak_20260723_232555;
DROP TABLE IF EXISTS order_withdrawal_bak_20260723_232555;
DROP TABLE IF EXISTS sys_menu_backup_before_remove_monitor_tool;
DROP TABLE IF EXISTS sys_menu_bak_20260723_232555;
DROP TABLE IF EXISTS sys_role_menu_backup_before_remove_monitor_tool;

-- Repair known schema comments that were previously imported with mojibake.
ALTER TABLE order_user
    MODIFY COLUMN sign_days INT NOT NULL DEFAULT 0 COMMENT '签到天数',
    MODIFY COLUMN total_sign_days INT NOT NULL DEFAULT 0 COMMENT '累计签到天数',
    MODIFY COLUMN today_sign_count INT NOT NULL DEFAULT 0 COMMENT '今日签到次数';
ALTER TABLE activity_account COMMENT = '活动账户';
ALTER TABLE activity_account_prize COMMENT = '活动账户奖品';
ALTER TABLE activity_info COMMENT = '活动信息';
ALTER TABLE activity_partner COMMENT = '活动合作方';
ALTER TABLE activity_prize
    MODIFY COLUMN kind CHAR(1) NOT NULL DEFAULT '1' COMMENT '1礼品 2现金 3抽奖次数',
    COMMENT = '活动奖品';
ALTER TABLE points_account COMMENT = '积分账户';
ALTER TABLE points_flow COMMENT = '积分流水';
ALTER TABLE points_gift
    MODIFY COLUMN kind CHAR(1) NOT NULL DEFAULT '1' COMMENT '1礼品 2现金',
    COMMENT = '积分礼品';
ALTER TABLE points_gift_order
    MODIFY COLUMN status CHAR(1) NOT NULL DEFAULT '1' COMMENT '1待发货 2已发货 3已收货 4已取消',
    COMMENT = '积分礼品订单';
ALTER TABLE website_customer COMMENT = '网站客户';
ALTER TABLE translations
    MODIFY COLUMN zh_CN TEXT COMMENT '中文(简体)',
    MODIFY COLUMN zh_TW TEXT COMMENT '中文(繁体)',
    MODIFY COLUMN ko_KR TEXT COMMENT '韩文',
    MODIFY COLUMN th_TH TEXT COMMENT '泰文',
    MODIFY COLUMN ja_JP TEXT COMMENT '日文',
    MODIFY COLUMN pt_PT TEXT COMMENT '葡萄牙语',
    MODIFY COLUMN en_US TEXT COMMENT '英文',
    MODIFY COLUMN ar_SA TEXT COMMENT '阿拉伯语',
    MODIFY COLUMN es_ES TEXT COMMENT '西班牙语',
    MODIFY COLUMN sv_SE TEXT COMMENT '瑞典语',
    MODIFY COLUMN it_IT TEXT COMMENT '意大利语',
    MODIFY COLUMN de_DE TEXT COMMENT '德语',
    MODIFY COLUMN no_NO TEXT COMMENT '挪威语',
    MODIFY COLUMN ru_RU TEXT COMMENT '俄语',
    MODIFY COLUMN hu_HU TEXT COMMENT '匈牙利语',
    MODIFY COLUMN pl_PL TEXT COMMENT '波兰语',
    MODIFY COLUMN sk_SK TEXT COMMENT '斯洛伐克语',
    MODIFY COLUMN fr_FR TEXT COMMENT '法语',
    MODIFY COLUMN cs_CZ TEXT COMMENT '捷克语',
    MODIFY COLUMN pt_BR TEXT COMMENT '巴西葡萄牙语',
    MODIFY COLUMN hi_IN TEXT COMMENT '印地语',
    COMMENT = '多语言翻译';
UPDATE order_config
SET name = CASE type
    WHEN 'error' THEN '错误代码'
    WHEN 'backendRateLimit' THEN '后端限流设置'
    WHEN 'frontendRateLimit' THEN '前端限流设置'
    ELSE name
END
WHERE type IN ('error', 'backendRateLimit', 'frontendRateLimit');
UPDATE sys_menu
SET remark = CASE menu_id
    WHEN 4000 THEN '积分商城目录'
    WHEN 4001 THEN '礼品管理目录'
    WHEN 4002 THEN '礼品管理菜单'
    WHEN 4003 THEN '积分账户目录'
    WHEN 4004 THEN '积分账户菜单'
    WHEN 4005 THEN '积分流水菜单'
    WHEN 4006 THEN '积分订单目录'
    WHEN 4007 THEN '积分订单菜单'
    WHEN 4100 THEN '活动管理目录'
    WHEN 4101 THEN '活动管理目录'
    WHEN 4102 THEN '活动管理菜单'
    WHEN 4103 THEN '奖品管理菜单'
    WHEN 4104 THEN '活动账户目录'
    WHEN 4105 THEN '活动账户菜单'
    WHEN 4106 THEN '参与记录菜单'
    WHEN 4200 THEN '官网管理目录'
    WHEN 4201 THEN '官网管理目录'
    WHEN 4202 THEN '客户管理菜单'
    ELSE remark
END
WHERE menu_id IN (
    4000, 4001, 4002, 4003, 4004, 4005, 4006, 4007,
    4100, 4101, 4102, 4103, 4104, 4105, 4106,
    4200, 4201, 4202
);

SELECT COUNT(*) AS goods_count FROM goods;
SELECT COUNT(*) AS goods_type_count FROM goods_type;
SELECT COUNT(*) AS missing_image_url_count
FROM goods
WHERE image IS NULL OR image = '';
