-- Generated by tools/migrate-old-levels.mjs
-- Source: https://g9p7q0i2-20260513.top/backend/marketing/levels/page
SET NAMES utf8mb4;
START TRANSACTION;

ALTER TABLE goods_member_level
    MODIFY COLUMN icon VARCHAR(500) CHARACTER SET utf8mb4
        COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '图标';

DROP TEMPORARY TABLE IF EXISTS tmp_old_member_level;
CREATE TEMPORARY TABLE tmp_old_member_level (
    source_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    level INT NOT NULL,
    icon VARCHAR(500) NOT NULL,
    price DECIMAL(20,2) NOT NULL,
    min_balance DECIMAL(20,2) NOT NULL,
    invite_count INT NOT NULL,
    order_count_per_day INT NOT NULL,
    min_commission_rate DECIMAL(5,2) NOT NULL,
    max_commission_rate DECIMAL(5,2) NOT NULL,
    min_continuous_commission_rate DECIMAL(5,2) NOT NULL,
    max_continuous_commission_rate DECIMAL(5,2) NOT NULL,
    task_count_per_day INT NOT NULL,
    withdraw_count_per_day INT NOT NULL,
    withdraw_fee_rate DECIMAL(5,2) NOT NULL,
    min_withdraw_amount DECIMAL(20,2) NOT NULL,
    withdraw_limit_per_day DECIMAL(20,2) NOT NULL,
    min_withdraw DECIMAL(20,2) NOT NULL,
    max_withdraw DECIMAL(20,2) NOT NULL,
    description TEXT NOT NULL,
    create_time DATETIME(3) NOT NULL,
    product_match_enabled CHAR(1) NOT NULL,
    product_match_min DECIMAL(5,2) NOT NULL,
    product_match_max DECIMAL(5,2) NOT NULL,
    PRIMARY KEY (level),
    UNIQUE KEY uk_tmp_old_member_level_source_id (source_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO tmp_old_member_level (
    source_id, name, level, icon, price, min_balance, invite_count,
    order_count_per_day, min_commission_rate, max_commission_rate,
    min_continuous_commission_rate, max_continuous_commission_rate,
    task_count_per_day, withdraw_count_per_day, withdraw_fee_rate,
    min_withdraw_amount, withdraw_limit_per_day, min_withdraw, max_withdraw,
    description, create_time, product_match_enabled, product_match_min,
    product_match_max
) VALUES
(1, 'VIP1', 1, '/profile/level/img/1dc5f6af397c61e141c7a0c9a94f6094.png', 100, 100, 999999, 40, 0.5, 0.5, 5, 5, 2, 10, 0, 40, 10000, 50, 10000, '<p><strong>●Suitable for most data capture scenarios involving light to medium usage</strong></p><p><strong>●Profit of 0.5% per product data</strong></p><p><strong>●40 product data per set</strong></p><p><strong>●Up to 80 data submissions per day</strong></p><p><strong>●Can complete 2 sets of data submissions per day</strong></p><p><strong>●No access to other Premium features</strong><br/></p>', '2023-11-26 13:24:20.000', '0', 0, 0),
(2, 'VIP2', 2, '/profile/level/img/d23b1b0cf5719af9b6108df30509fb32.png', 500, 500, 999999, 45, 1, 1, 10, 10, 2, 10, 0, 45, 30000, 50, 30000, '<p><strong>●Premium user have limited access to all features of the platform</strong></p><p><strong>●Deposit according to our events</strong></p><p><strong>●Profit of 1.0% per product data</strong></p><p><strong>●45 product data per set</strong></p><p><strong>●Up to 90 product data per day</strong></p><p><strong>●Can complete 2 sets of data submissions per day</strong></p><p><strong>●Better profit and permission</strong></p><p><strong>●Full access to all other premium features</strong></p>', '2023-11-30 04:48:39.000', '0', 0, 0),
(3, 'VIP3', 3, '/profile/level/img/396d4d8f86b946176c664f6884fd170a.png', 1600, 1600, 999999, 50, 1.5, 1.5, 15, 15, 2, 10, 0, 50, 500000, 50, 500000, '<p><strong>●Premium user have limited access to all features of the platform</strong></p><p><strong>●Deposit according to our events</strong></p><p><strong>●Profit of 1.5% per product data</strong></p><p><strong>●50 product data per set</strong></p><p><strong>●Up to 100 product data per day</strong></p><p><strong>●Can complete 2 sets of data submissions per day</strong></p><p><strong>●Better profit and permission</strong></p><p><strong>●Full access to all other premium features</strong></p>', '2023-11-30 04:49:11.000', '0', 0, 0),
(4, 'VIP4', 4, '/profile/level/img/910f3447505ef76a2c179229079f0d12.png', 5500, 5500, 999999, 55, 2, 2, 20, 20, 2, 10, 0, 55, 1000000, 50, 1000000, '<p><strong>●Premium user have limited access to all features of the platform</strong></p><p><strong>●Deposit according to our events</strong></p><p><strong>●Profit of 2.0% per product data</strong></p><p><strong>●55 product data per set</strong></p><p><strong>●Up to 110 product data per day</strong></p><p><strong>●Can complete 2 sets of data submissions per day</strong></p><p><strong>●Better profit and permission</strong></p><p><strong>●Full access to all other premium features</strong></p>', '2025-03-21 18:43:03.000', '0', 0, 0),
(5, 'VIP5', 5, '/profile/level/img/738415df5afb10b01f90539c586c7373.png', 10000, 10000, 999999, 60, 2.5, 2.5, 25, 25, 2, 10, 0, 60, 1000000, 50, 1000000, '<p><strong>●Supreme user gets unlimited access to all features of the platform</strong></p><p><strong>●Deposits according to our events</strong></p><p><strong>●Profit of 2.5% per product data</strong></p><p><strong>●60 product data per set</strong></p><p><strong>●Up to 120 product data per day</strong></p><p><strong>●Can complete 2 set of data submissions per day</strong></p><p><strong>●Better profits and permissions </strong></p><p><strong>●Full access to all other premium features</strong></p>', '2025-03-21 18:44:07.000', '0', 0, 0);

UPDATE goods_member_level target
JOIN tmp_old_member_level source ON source.level = target.level
SET target.name = source.name,
    target.icon = source.icon,
    target.price = source.price,
    target.min_balance = source.min_balance,
    target.invite_count = source.invite_count,
    target.order_count_per_day = source.order_count_per_day,
    target.min_commission_rate = source.min_commission_rate,
    target.max_commission_rate = source.max_commission_rate,
    target.min_continuous_commission_rate =
        source.min_continuous_commission_rate,
    target.max_continuous_commission_rate =
        source.max_continuous_commission_rate,
    target.task_count_per_day = source.task_count_per_day,
    target.withdraw_count_per_day = source.withdraw_count_per_day,
    target.withdraw_fee_rate = source.withdraw_fee_rate,
    target.min_withdraw_amount = source.min_withdraw_amount,
    target.withdraw_limit_per_day = source.withdraw_limit_per_day,
    target.min_withdraw = source.min_withdraw,
    target.max_withdraw = source.max_withdraw,
    target.description = source.description,
    target.create_time = source.create_time,
    target.product_match_enabled = source.product_match_enabled,
    target.product_match_min = source.product_match_min,
    target.product_match_max = source.product_match_max;

INSERT INTO goods_member_level (
    name, level, icon, price, min_balance, invite_count, order_count_per_day,
    min_commission_rate, max_commission_rate, min_continuous_commission_rate,
    max_continuous_commission_rate, task_count_per_day, withdraw_count_per_day,
    withdraw_fee_rate, min_withdraw_amount, withdraw_limit_per_day,
    min_withdraw, max_withdraw, description, create_time,
    product_match_enabled, product_match_min, product_match_max
)
SELECT source.name, source.level, source.icon, source.price, source.min_balance,
       source.invite_count, source.order_count_per_day,
       source.min_commission_rate, source.max_commission_rate,
       source.min_continuous_commission_rate,
       source.max_continuous_commission_rate, source.task_count_per_day,
       source.withdraw_count_per_day, source.withdraw_fee_rate,
       source.min_withdraw_amount, source.withdraw_limit_per_day,
       source.min_withdraw, source.max_withdraw, source.description,
       source.create_time, source.product_match_enabled,
       source.product_match_min, source.product_match_max
FROM tmp_old_member_level source
LEFT JOIN goods_member_level target ON target.level = source.level
WHERE target.id IS NULL;

DELETE target
FROM goods_member_level target
LEFT JOIN tmp_old_member_level source ON source.level = target.level
LEFT JOIN order_user user_ref ON user_ref.vip_id = target.id
WHERE source.level IS NULL
  AND user_ref.id IS NULL;

COMMIT;

SELECT id, name, level, icon, price, min_balance, invite_count,
       order_count_per_day, min_commission_rate, max_commission_rate,
       min_continuous_commission_rate, max_continuous_commission_rate,
       task_count_per_day, withdraw_count_per_day, withdraw_fee_rate,
       min_withdraw_amount, withdraw_limit_per_day, min_withdraw, max_withdraw,
       product_match_enabled, product_match_min, product_match_max
FROM goods_member_level
ORDER BY level, id;
